name: py39
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - cudatoolkit=11.1.74
  - matplotlib=3.4.2
  - numpy=1.19.2
  - pandas=1.3.1
  - pip
  - python=3.9.6
  - pytorch=1.9.0
  - termcolor=1.1.0
  - torchaudio=0.9.0
  - torchvision=0.10.0
  - tqdm=4.62.1
  - requests
  - pip:
    - llvmlite==0.38.0
    - numba==0.55.1
    - scikit-learn==1.0.1
    - scipy==1.7.1
    - faiss-gpu==1.7.1
